-- lifelaw-monitor-web : Web 소유 스키마 (TW_) create-only 마이그레이션 0001
--
-- 권위 : DESIGN_lifelaw_monitor_web_admin_architecture_v1_2.md (APPROVED)
--          §7.2 Web 소유 테이블 (A-03·A-09 승인)
--          §9   관리 명령 Inbox 스키마
--          §17  RBAC 역할 6종·권한 14종 (A-05 승인)
--          §17.4 서버 측 세션 (A-04 승인)
--          §18  위험 등급별 승인
--          §19  감사와 멱등성
--        docs/contracts/db-contract.md  (명명·타입 규약)
--        DESIGN_project_structure_and_toolchain_v0_1.md §8 (마이그레이션 방식)
--
-- 규약 : 코드 컬럼은 *_cd, 시각은 TIMESTAMPTZ(3), 등록·수정은 reg_dt/mod_dt.
--        단 TW_ADMIN_COMMAND 의 command_type / status 는 설계 §9 가 그 이름으로
--        명시했으므로 설계를 따른다.
--
-- 소유 : 이 스크립트의 모든 객체 소유자는 lifelaw_web_migrator 다.
--        수집기 소유 테이블(TC_/TN_/TH_)은 이 스크립트가 건드리지 않는다.
--
-- 성격 : non-idempotent. 이미 존재하면 실패한다. 재적용하지 않는다.

BEGIN;

-- ---------------------------------------------------------------------------
-- 마이그레이션 적용 원장
-- ---------------------------------------------------------------------------

CREATE TABLE TW_SCHEMA_MIGRATION (
    version      VARCHAR(20)    NOT NULL,
    filename     VARCHAR(200)   NOT NULL,
    checksum     CHAR(64)       NOT NULL,
    applied_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    applied_by   VARCHAR(100)   NOT NULL DEFAULT current_user,
    CONSTRAINT pk_tw_schema_migration PRIMARY KEY (version)
);

COMMENT ON TABLE TW_SCHEMA_MIGRATION IS 'TW_ 스키마 마이그레이션 적용 원장';
COMMENT ON COLUMN TW_SCHEMA_MIGRATION.checksum IS '적용 시점 SQL 파일 SHA-256. 불일치 시 재적용을 거부한다';

-- ---------------------------------------------------------------------------
-- 계정
-- ---------------------------------------------------------------------------

CREATE TABLE TW_USER (
    user_id          BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    login_id         VARCHAR(100)   NOT NULL,
    user_nm          VARCHAR(100)   NOT NULL,
    password_hash    VARCHAR(255)   NOT NULL,
    use_yn           CHAR(1)        NOT NULL DEFAULT 'Y',
    pwd_changed_at   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    last_login_at    TIMESTAMPTZ(3),
    failed_login_cnt INTEGER        NOT NULL DEFAULT 0,
    locked_until     TIMESTAMPTZ(3),
    reger            VARCHAR(100)   NOT NULL,
    reg_dt           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    moder            VARCHAR(100)   NOT NULL,
    mod_dt           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    CONSTRAINT pk_tw_user PRIMARY KEY (user_id),
    CONSTRAINT uk_tw_user_login UNIQUE (login_id),
    CONSTRAINT ck_tw_user_use_yn CHECK (use_yn IN ('Y', 'N')),
    CONSTRAINT ck_tw_user_failed_cnt CHECK (failed_login_cnt >= 0),
    -- 평문·짧은 해시 유입 방지. Argon2id 인코딩 문자열만 허용한다.
    CONSTRAINT ck_tw_user_pwd_argon2 CHECK (password_hash LIKE '$argon2id$%')
);

COMMENT ON TABLE TW_USER IS '관리자 계정. 삭제하지 않고 use_yn=N 으로 비활성화한다';
COMMENT ON COLUMN TW_USER.password_hash IS 'Argon2id 인코딩 해시. 평문·가역 암호 저장 금지';
COMMENT ON COLUMN TW_USER.failed_login_cnt IS '연속 로그인 실패 횟수. 성공 시 0으로 초기화';
COMMENT ON COLUMN TW_USER.locked_until IS '무차별 대입 방어 잠금 해제 시각';

-- ---------------------------------------------------------------------------
-- RBAC — 역할 6종 · 권한 14종 (설계 §17, A-05 승인)
-- ---------------------------------------------------------------------------

CREATE TABLE TW_ROLE (
    role_cd    VARCHAR(30)    NOT NULL,
    role_nm    VARCHAR(100)   NOT NULL,
    role_desc  VARCHAR(500),
    sort_ord   NUMERIC(5,0)   NOT NULL DEFAULT 0,
    reg_dt     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    CONSTRAINT pk_tw_role PRIMARY KEY (role_cd)
);

CREATE TABLE TW_PERMISSION (
    perm_cd    VARCHAR(50)    NOT NULL,
    perm_nm    VARCHAR(100)   NOT NULL,
    sort_ord   NUMERIC(5,0)   NOT NULL DEFAULT 0,
    reg_dt     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    CONSTRAINT pk_tw_permission PRIMARY KEY (perm_cd)
);

CREATE TABLE TW_ROLE_PERMISSION (
    role_cd  VARCHAR(30)    NOT NULL,
    perm_cd  VARCHAR(50)    NOT NULL,
    reg_dt   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    CONSTRAINT pk_tw_role_permission PRIMARY KEY (role_cd, perm_cd),
    CONSTRAINT fk_tw_role_permission_role FOREIGN KEY (role_cd)
        REFERENCES TW_ROLE (role_cd),
    CONSTRAINT fk_tw_role_permission_perm FOREIGN KEY (perm_cd)
        REFERENCES TW_PERMISSION (perm_cd)
);

CREATE TABLE TW_USER_ROLE (
    user_id  BIGINT         NOT NULL,
    role_cd  VARCHAR(30)    NOT NULL,
    reger    VARCHAR(100)   NOT NULL,
    reg_dt   TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    CONSTRAINT pk_tw_user_role PRIMARY KEY (user_id, role_cd),
    CONSTRAINT fk_tw_user_role_user FOREIGN KEY (user_id)
        REFERENCES TW_USER (user_id),
    CONSTRAINT fk_tw_user_role_role FOREIGN KEY (role_cd)
        REFERENCES TW_ROLE (role_cd)
);

COMMENT ON TABLE TW_ROLE IS '역할. 설계 §17.1 의 6종이 전체 집합이며 추가는 설계 개정 사항';
COMMENT ON TABLE TW_PERMISSION IS '권한. 설계 §17.2 의 14종이 전체 집합. 임의 문자열을 권한으로 받지 않는다';
COMMENT ON TABLE TW_ROLE_PERMISSION IS '역할-권한 부여. default-deny 이므로 여기 없는 조합은 거부된다';

INSERT INTO TW_ROLE (role_cd, role_nm, role_desc, sort_ord) VALUES
  ('VIEWER',         '조회자',       '조회 전용',                     10),
  ('OPERATOR',       '운영자',       '조회 + 관리 명령 신청',          20),
  ('POLICY_MANAGER', '정책관리자',   '운영자 + 수집 정책 변경',        30),
  ('APPROVER',       '승인자',       '조회 + 고위험 명령 승인',        40),
  ('ADMIN',          '시스템관리자', '조회 + 계정·역할 관리',          50),
  ('AUDITOR',        '감사자',       '조회 + 감사 로그 열람. 변경 권한 없음', 60);

INSERT INTO TW_PERMISSION (perm_cd, perm_nm, sort_ord) VALUES
  ('target:read',         '대상 목록·상세 조회',   10),
  ('target:history:read', '대상 변경 이력 조회',   20),
  ('batch:read',          '배치 실행 원장 조회',   30),
  ('policy:read',         '수집 정책 조회',        40),
  ('policy:site:write',   '사이트 정책 변경',      50),
  ('policy:target:write', '대상 직접 정책 변경',   60),
  ('command:rerun',       '배치 rerun 신청',       70),
  ('command:cancel',      '배치 취소 신청',        80),
  ('command:reset',       '개별 대상 재처리 신청', 90),
  ('command:resync',      'R 마스터 재동기화 신청', 100),
  ('command:approve',     '고위험 명령 승인',      110),
  ('artifact:read',       '수집 아티팩트 열람',    120),
  ('audit:read',           '감사 로그 열람',        130),
  ('user:manage',         '계정·역할 관리',        140);

-- 역할-권한 부여.
--
-- 근거는 DESIGN_admin_screen_inventory_v0_1.md §5 화면-권한 매트릭스다(사용자
-- 확인 2026-08-06). 매트릭스는 **누적이 아니다** — 상위 역할이 하위 역할의
-- 쓰기 권한을 자동으로 갖지 않는다. 특히 ADMIN 에게 command:approve 를 주지
-- 않는다. 주면 계정 관리자가 자기 신청을 승인할 수 있어 §17.3 4-eyes 가
-- 무너진다.
--
-- artifact:read 는 A-08(아티팩트 열람 정책) 미승인이므로 어떤 역할에도
-- 부여하지 않는다. 매트릭스의 '○' 표기가 그 뜻이다.
--
-- command:resync 는 설계에 대응 화면이 없어 부여 대상이 불명확하다.
-- 현재 어떤 역할에도 부여하지 않는다. OPEN QUESTION 으로 보고한다.

INSERT INTO TW_ROLE_PERMISSION (role_cd, perm_cd)
SELECT r.role_cd, p.perm_cd
  FROM (VALUES
        ('VIEWER'), ('OPERATOR'), ('POLICY_MANAGER'),
        ('APPROVER'), ('ADMIN'), ('AUDITOR')
       ) AS r(role_cd)
  CROSS JOIN (VALUES
        ('target:read'), ('target:history:read'),
        ('batch:read'), ('policy:read')
       ) AS p(perm_cd);

INSERT INTO TW_ROLE_PERMISSION (role_cd, perm_cd) VALUES
  ('OPERATOR',       'command:rerun'),
  ('OPERATOR',       'command:cancel'),
  ('OPERATOR',       'command:reset'),
  ('POLICY_MANAGER', 'command:rerun'),
  ('POLICY_MANAGER', 'command:cancel'),
  ('POLICY_MANAGER', 'command:reset'),
  ('POLICY_MANAGER', 'policy:site:write'),
  ('POLICY_MANAGER', 'policy:target:write'),
  ('APPROVER',       'command:approve'),
  ('ADMIN',          'user:manage'),
  ('AUDITOR',        'audit:read');

-- ---------------------------------------------------------------------------
-- 세션 (설계 §17.4, A-04 승인)
-- ---------------------------------------------------------------------------

CREATE TABLE TW_SESSION (
    session_token_hash  CHAR(64)       NOT NULL,
    user_id             BIGINT         NOT NULL,
    csrf_token_hash     CHAR(64)       NOT NULL,
    source_ip           VARCHAR(45),
    user_agent          VARCHAR(500),
    created_at          TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    last_seen_at        TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    absolute_expires_at TIMESTAMPTZ(3) NOT NULL,
    reauth_at           TIMESTAMPTZ(3),
    CONSTRAINT pk_tw_session PRIMARY KEY (session_token_hash),
    CONSTRAINT fk_tw_session_user FOREIGN KEY (user_id)
        REFERENCES TW_USER (user_id),
    CONSTRAINT ck_tw_session_expiry CHECK (absolute_expires_at > created_at)
);

CREATE INDEX ix_tw_session_user ON TW_SESSION (user_id);
CREATE INDEX ix_tw_session_expiry ON TW_SESSION (absolute_expires_at);

COMMENT ON TABLE TW_SESSION IS '서버 측 세션. 로그아웃·권한 변경 시 행을 삭제해 즉시 무효화한다';
COMMENT ON COLUMN TW_SESSION.session_token_hash IS
  '세션 토큰의 SHA-256. 원본 토큰을 저장하지 않는다. DB 유출만으로 세션을 탈취할 수 없게 한다';
COMMENT ON COLUMN TW_SESSION.last_seen_at IS '유휴 만료 계산 기준. 요청마다 갱신되는 유일한 컬럼';
COMMENT ON COLUMN TW_SESSION.reauth_at IS '재인증 완료 시각. 최고 위험 작업은 이 값의 신선도를 검사한다';

-- ---------------------------------------------------------------------------
-- 관리 명령 Inbox (설계 §9)
-- ---------------------------------------------------------------------------

CREATE TABLE TW_ADMIN_COMMAND (
    command_id       BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    command_type     VARCHAR(30)    NOT NULL,
    payload          JSONB          NOT NULL,
    idempotency_key  VARCHAR(200)   NOT NULL,
    requested_by     VARCHAR(100)   NOT NULL,
    requested_reason VARCHAR(1000)  NOT NULL,
    approved_by      VARCHAR(100),
    status           VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    expires_at       TIMESTAMPTZ(3) NOT NULL,
    result_msg       VARCHAR(1000),
    reg_dt           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    mod_dt           TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    CONSTRAINT pk_tw_admin_command PRIMARY KEY (command_id),
    CONSTRAINT uk_tw_admin_command_idem UNIQUE (idempotency_key),
    CONSTRAINT ck_tw_admin_command_type CHECK (command_type IN (
        'RERUN_BATCH', 'CANCEL_BATCH', 'RESET_TARGET', 'RESYNC_R_MASTER')),
    CONSTRAINT ck_tw_admin_command_status CHECK (status IN (
        'PENDING', 'ACCEPTED', 'REJECTED', 'IN_PROGRESS',
        'DONE', 'FAILED', 'EXPIRED')),
    CONSTRAINT ck_tw_admin_command_reason CHECK (btrim(requested_reason) <> ''),
    CONSTRAINT ck_tw_admin_command_expiry CHECK (expires_at > reg_dt),
    -- payload 는 객체여야 한다. 배열·스칼라 유입을 막는다.
    CONSTRAINT ck_tw_admin_command_payload CHECK (jsonb_typeof(payload) = 'object'),
    -- 4-eyes: 신청자와 승인자는 같을 수 없다. 애플리케이션 검사에 의존하지 않는다.
    CONSTRAINT ck_tw_admin_command_four_eyes CHECK (
        approved_by IS NULL OR approved_by <> requested_by)
);

CREATE INDEX ix_tw_admin_command_status ON TW_ADMIN_COMMAND (status, expires_at);
CREATE INDEX ix_tw_admin_command_type ON TW_ADMIN_COMMAND (command_type, status);

COMMENT ON TABLE TW_ADMIN_COMMAND IS
  '관리 명령 Inbox. Web 은 PENDING 행을 INSERT 만 하고, 이후 상태 전이는 소비자(수집기)가 수행한다';
COMMENT ON COLUMN TW_ADMIN_COMMAND.idempotency_key IS
  '중복 제출 차단. UNIQUE 제약으로 강제하며 애플리케이션 체크에 의존하지 않는다';
COMMENT ON COLUMN TW_ADMIN_COMMAND.expires_at IS
  '만료 시각. 어제 신청한 RERUN_BATCH 가 오늘 실행되는 것을 막는다';
COMMENT ON COLUMN TW_ADMIN_COMMAND.status IS
  'PENDING 은 "대기 중"이 아니라 "미처리"다. 소비자 미구현 상태에서는 영구히 PENDING 에 남는다';

-- ---------------------------------------------------------------------------
-- 승인 원장 (설계 §18)
-- ---------------------------------------------------------------------------

CREATE TABLE TW_APPROVAL (
    approval_id        BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    command_id         BIGINT         NOT NULL,
    risk_level_cd      VARCHAR(10)    NOT NULL,
    requested_by       VARCHAR(100)   NOT NULL,
    approver           VARCHAR(100)   NOT NULL,
    decision_cd        VARCHAR(20)    NOT NULL,
    decision_reason    VARCHAR(1000)  NOT NULL,
    reauth_verified_yn CHAR(1)        NOT NULL DEFAULT 'N',
    decided_at         TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    CONSTRAINT pk_tw_approval PRIMARY KEY (approval_id),
    CONSTRAINT fk_tw_approval_command FOREIGN KEY (command_id)
        REFERENCES TW_ADMIN_COMMAND (command_id),
    CONSTRAINT ck_tw_approval_risk CHECK (risk_level_cd IN (
        'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_tw_approval_decision CHECK (decision_cd IN (
        'APPROVED', 'REJECTED')),
    CONSTRAINT ck_tw_approval_reauth_yn CHECK (reauth_verified_yn IN ('Y', 'N')),
    CONSTRAINT ck_tw_approval_reason CHECK (btrim(decision_reason) <> ''),
    -- 4-eyes 를 DB 에서 강제한다.
    CONSTRAINT ck_tw_approval_four_eyes CHECK (approver <> requested_by),
    -- CRITICAL 승인은 재인증 없이 성립할 수 없다(설계 §18 최고 등급).
    CONSTRAINT ck_tw_approval_critical_reauth CHECK (
        risk_level_cd <> 'CRITICAL'
        OR decision_cd = 'REJECTED'
        OR reauth_verified_yn = 'Y')
);

CREATE INDEX ix_tw_approval_command ON TW_APPROVAL (command_id);

COMMENT ON TABLE TW_APPROVAL IS '승인 원장. append-only. 결정을 수정하지 않고 새 행을 남긴다';
COMMENT ON COLUMN TW_APPROVAL.risk_level_cd IS
  '설계 §18 위험 등급. LOW 저 / MEDIUM 중 / HIGH 고 / CRITICAL 최고';
COMMENT ON COLUMN TW_APPROVAL.reauth_verified_yn IS
  '재인증 확인 여부. CRITICAL 승인에는 Y 가 강제된다';

-- ---------------------------------------------------------------------------
-- 감사 로그 (설계 §19.1) — append-only
-- ---------------------------------------------------------------------------

CREATE TABLE TW_AUDIT_LOG (
    audit_id        BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    occurred_at     TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
    actor           VARCHAR(100)   NOT NULL,
    actor_role_cd   VARCHAR(30),
    source_ip       VARCHAR(45),
    user_agent      VARCHAR(500),
    action          VARCHAR(100)   NOT NULL,
    target_type     VARCHAR(50),
    target_id       VARCHAR(100),
    before_value    JSONB,
    after_value     JSONB,
    reason          VARCHAR(1000),
    approval_id     BIGINT,
    idempotency_key VARCHAR(200),
    result_cd       VARCHAR(20)    NOT NULL,
    CONSTRAINT pk_tw_audit_log PRIMARY KEY (audit_id),
    CONSTRAINT ck_tw_audit_log_result CHECK (result_cd IN (
        'SUCCESS', 'DENIED', 'FAILED', 'TIMEOUT'))
);

CREATE INDEX ix_tw_audit_log_occurred ON TW_AUDIT_LOG (occurred_at);
CREATE INDEX ix_tw_audit_log_actor ON TW_AUDIT_LOG (actor, occurred_at);
CREATE INDEX ix_tw_audit_log_target ON TW_AUDIT_LOG (target_type, target_id);

COMMENT ON TABLE TW_AUDIT_LOG IS
  'append-only 감사 로그. 런타임 롤에 UPDATE/DELETE 를 부여하지 않는다. 애플리케이션 규율만으로는 부족하다';
COMMENT ON COLUMN TW_AUDIT_LOG.result_cd IS
  '실패한 시도도 기록한다. DENIED 권한 거부 / TIMEOUT 배리어 경합';
COMMENT ON COLUMN TW_AUDIT_LOG.before_value IS '변경 전 값. 비밀번호·토큰·DSN 은 마스킹해 저장한다';
COMMENT ON COLUMN TW_AUDIT_LOG.after_value IS '변경 후 값. 비밀번호·토큰·DSN 은 마스킹해 저장한다';

-- approval_id 는 FK 를 걸지 않는다. 감사 로그는 승인 원장보다 오래 남아야 하고,
-- 승인 없이 발생한 사건(권한 거부 등)도 기록하기 때문이다.

COMMIT;
